services:
  artemis:
    container_name: artemis-app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped

  cloudflared:
    container_name: artemis-cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - artemis
